### ISSUE TITLE
Count function doesn't return correct number of elements in range

### ISSUE THREAD

**Issue by Kristine1975** [eriksvedang/Sprak#2]
The following code should print `51` and `52`. It does, however, print `51` and `51`.

```
Print(Count(Range(0, 50)))
Print(Count(Range(0, 51)))
```

The cause is a bug in the built-in function `Count`, which returns the number of elements in an array, in a string, or in a range created by the built-in function `Range`. However it incorrectly considers a range to be `[min..max)` instead of `[min..max]`, leaving out the `max` element. Thus the current implementation of `Count` returns one element too little.

The reason lies in the following line, which should be `r.end - r.start + 1` to include the range's `max` element.

https://github.com/eriksvedang/Sprak/blob/6e0340b5d5a27ebc78cc44f36cf4fb545bf42ddf/ProgrammingLanguageNr1/src/5.%20Run/SprakRunner.cs#L416

As the `Range` function only creates a real range (a C# `Range` object) when the range contains more than 50 elements (it creates an array otherwise), this bug only manifests itself with bigger ranges.

**Comment by eriksvedang** [comment]
Oh, thanks for the find! 
Do you feel like fixing this? @Kristine1975 
I can do it otherwise, of course...

**Comment by Kristine1975** [comment]
I've created pull request #3 with a fix.

**Comment by eriksvedang** [comment]
Awesome.
